### PR TITLE
Pypi Release

### PR DESCRIPTION
**Pull request by cherriae**
The current `pyproject.toml` doesn't have your email you have to add it manually.

```py
authors = [
    { name="TrueMyst", email="urEmailHere" }
]
```

- Fixed a typo in `README.md` 
`**BeatPrints** is released under the **Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License license**, which grants the following permissions:`

> There were 2 license: `... License liscense`

### CODE REVIEW

**Comment by cherriae** [comment]
I saw #11 so I decided to do it for you cuz you haven't yet

**Comment by cherriae** [comment]
I've converted `src` directory name to `beatprints` and added `__init__.py` and `__main__.py`

**Comment by TrueMyst** [comment]
Amazing work Jerry! Really appreciate the work, I'm fixing a couple of bugs from my side, will push it within a day or two! :)

**Comment by cherriae** [comment]
There gonna be a big issue with lyrics soon @TrueMyst there seems to be a rate limit

**Comment by cherriae** [comment]
I'm also doing some research on getting non python files downloaded too but the problem how do u access the fonts

**Comment by TrueMyst** [comment]
> There gonna be a big issue with lyrics soon @TrueMyst there seems to be a rate limit

Don't you worry, I've moved on from MusixMatch because I've found a better alternative to this. You'll see it very soon!

**Comment by TrueMyst** [comment]
> I'm also doing some research on getting non python files downloaded too but the problem how do u access the fonts

How do I access the fonts? Can you elaborate it more please?

**Comment by cherriae** [comment]
> > I'm also doing some research on getting non python files downloaded too but the problem how do u access the fonts
> 
> How do I access the fonts? Can you elaborate it more please?

If I download the package and generate a print how do I access the fonts or is it that I can use custom fonts?

**Comment by cherriae** [comment]
> > I'm also doing some research on getting non python files downloaded too but the problem how do u access the fonts
> 
> How do I access the fonts? Can you elaborate it more please?

I was thinking about how the fonts will be accessed through packages. This is because when ur installing the package how does the package access the fonts

**Comment by cherriae** [comment]
Also instead of `pyproject.toml` I could do `setuptools` if u want or find more better

**Comment by TrueMyst** [comment]
> I was thinking about how the fonts will be accessed through packages. This is because when ur installing the package how does the package access the fonts

https://setuptools.pypa.io/en/latest/userguide/datafiles.html

**Comment by TrueMyst** [comment]
> Also instead of `pyproject.toml` I could do `setuptools` if u want or find more better

Yeah, setuptools will do me better!

**Comment by TrueMyst** [comment]
@cherriae I've updated the code a bit, you might want to check it out.

**Comment by TrueMyst** [comment]
> I was thinking about how the fonts will be accessed through packages. This is because when ur installing the package how does the package access the fonts

I'm concerned about the current setup in `utils.py` where I manually set the fonts. Whenever there's an issue with fonts, I have to manually add them and then repackage the module for PyPi. While I considered letting users add their own fonts, I worry they might change the appearance too much.

Instead, I'm thinking of providing default fonts from my code. For instance, if a user needs a font for Hindi but it's not available, they can specify the file path to add it themselves

I've to modify and optimize `writing.py` a bit.

**Comment by cherriae** [comment]
> > I was thinking about how the fonts will be accessed through packages. This is because when ur installing the package how does the package access the fonts
> 
> I'm concerned about the current setup in `utils.py` where I manually set the fonts. Whenever there's an issue with fonts, I have to manually add them and then repackage the module for PyPi. While I considered letting users add their own fonts, I worry they might change the appearance too much.
> 
> Instead, I'm thinking of providing default fonts from my code. For instance, if a user needs a font for Hindi but it's not available, they can specify the file path to add it themselves
> 
> I've to modify and optimize `writing.py` a bit.

Yeah its probably better to let them customize on their own.

**Comment by cherriae** [comment]
Opening a new pr soon

**Comment by TrueMyst** [comment]
> Opening a new pr soon

Alright mate : ) lemme know if you need any help

**Pull request closed without merging**
