### PR TITLE
Add album posters + minor fixes

### PR DESCRIPTION
**Pull request by itsnotrin**
This closes issue #16.

There are some little bugs still with album image generation but it's good enough to PR and merge in imo
Any suggestions are welcome.

requirements.txt was also missing so I added back one from a previous commit that works.

### CODE REVIEW

**Comment by RUGMJ** [comment]
lgtm

**Comment by TrueMyst** [comment]
Hey! I cloned your repo and noticed a few bugs I’ll need to fix. My exams are going on right now, but I’ll get to it as soon as possible. Also, just a heads up we’re using Poetry instead of requirements.txt :>

**Comment by itsnotrin** [comment]
Gotcha, sorry about that I just noticed one with turning off the accent colour too. 

Sorry about the requirements too lol

**Comment by TrueMyst** [comment]
I have a lot to do in order to prepare this pull request. On top of that, I need to design an attractive album poster. Packaging it up is also challenging, especially with my exams coming up.

**Comment by TrueMyst** [comment]
But this provides me a head start for me to work on it :>

**Comment by itsnotrin** [comment]
Understandable lol 
For now I think it looks good as i've just copied the song posters pretty much 1:1

**Comment by TrueMyst** [comment]
Could you also generate an album poster and show me? That'll be really helpful

**Comment by RUGMJ** [comment]
A picture @itsnotrin sent me before image

**Comment by itsnotrin** [comment]
Here's a bunch which I printed off for my wall:

imageimageimageimageimageimageimageimage

**Comment by TrueMyst** [comment]
This is absolutely perfect! I'll just clone your repo and tidy up the code a bit.

(Also, love that you printed them out! :>)

**Comment by itsnotrin** [comment]
Glad I could help 😀

**Comment by TrueMyst** [comment]
lily_of_the_valley_by_daniel_973

Dark mode looks a bit gruvboxish, so tried to fix the colors :>

**Comment by itsnotrin** [comment]
Looks very pretty :)

**Comment by itsnotrin** [comment]
Got around to putting the posters up on the wall:
IMG_0359
IMG_0361

Can confirm they look good :)

**Comment by TrueMyst** [comment]
WOAH!!! they look so lovely (i'm so proud of myself)

**Comment by TrueMyst** [comment]
I'm just clearing up some code right now, hoping to finish it by today and create a PR to your repo:>

**Comment by itsnotrin** [comment]
Gotcha, I should be able to look at it tonight too :)

**Comment by TrueMyst** [comment]
I've encountered a really interesting bug that I can't seem to fix. For certain albums, when the index number is removed, the text sometimes shifts up slightly. Adding the index back in resolves the issue

summer_flows_0 02_by_wave_to_earth_47a
summer_flows_0 02_by_wave_to_earth_c40

**Comment by itsnotrin** [comment]
Woah that's uh really really odd lol, would you like to try fix it or do you want me to take a crack at it?

**Comment by TrueMyst** [comment]
golden_by_jung_kook_6e4
petals_to_thorns_by_d4vd_f02
the_black_parade_by_my_chemical_romance_ec8


I've made adjustments so that the offset is applied dynamically to the text (so that you don't have to hardcode it), and any tracks with excessively long names are removed to prevent issues.

**Comment by itsnotrin** [comment]
I agree it looks better
Perhaps we should an option for having track numbers on/off? Some people might prefer it

**Comment by TrueMyst** [comment]
On it! Do remember that adding indexing would take extra little spaces :>

**Comment by TrueMyst** [comment]
I’ve created a PR. Could you please review it and provide any feedback? It would be really helpful! :>

**Comment by itsnotrin** [comment]
Gave it a quick read and it looks good to me 😄 

I'll test it later and look a bit more in depth, thank you!

**Comment by TrueMyst** [comment]
Great! let's merge it then!

**Comment by TrueMyst** [comment]
@itsnotrin I've released BeatPrints to PyPi, feel free to check it out :>

**Pull request merged**
