### PR TITLE
writing: support for hindi

### PR DESCRIPTION
**Pull request by T-Dynamos**

### CODE REVIEW

**Comment by TrueMyst** [comment]
You're forgetting something. For english-based text, I'm using Oswald for that. I don't prefer using Noto-Sans. Could you review your code again and make a new change to it?

**Comment by T-Dynamos** [comment]
```
[['NAACHO NAACHO (FROM "RRR")', './assets/fonts/Oswald/Oswald-Bold.ttf']]
[['Vishal Mishra', './assets/fonts/Oswald/Oswald-Regular.ttf']]
[['03:34', './assets/fonts/Oswald/Oswald-Regular.ttf']]
[['नाचो, नाचो-नाचो, नाचो-नाचो, नाचो, वीरे, नाचो', './assets/fonts/NotoSans/NotoSans-Light.ttf']]
[['नाचो, नाचो-नाचो, नाचो-नाचो, नाचो, यारा, नाचो', './assets/fonts/NotoSans/NotoSans-Light.ttf']]
[['नाचो, नाचो-नाचो, आ दोबारा राग छेड़ा, नाचो', './assets/fonts/NotoSans/NotoSans-Light.ttf']]
[['नाचो, नाचो-नाचो, उसने चखा लागे तीखा, नाचो', './assets/fonts/NotoSans/NotoSans-Light.ttf']]
[['October 22, 2022', './assets/fonts/Oswald/Oswald-Regular.tt
f']]
[['T-Series', './assets/fonts/Oswald/Oswald-Regular.ttf']]
```

It is using Oswald indeed.

**Comment by TrueMyst** [comment]
Oh, my bad so you're using Noto Sans for Hindi? Ah- I was using Noto Sans Devanagari for Hindi text.

**Comment by T-Dynamos** [comment]
husn_by_anuv_jain_8254

**Comment by TrueMyst** [comment]
Looks good to me, but there seems to be an issue with the spacing.
image

This was not supposed to be like that.

It was supposed to be like this.
image

There should be a space in between, do you think you've change the co-ordinates or something?

**Comment by T-Dynamos** [comment]
No, you need to increase spacing a little bit, this behavior is default. We have to subtract y value from bounding box of font to from original y. (to support multilangs)

**Comment by TrueMyst** [comment]
image

On line 84, it should be `chunks.append(...)`, if you fix that, that'll be it.

**Comment by T-Dynamos** [comment]
> On line 84, it should be chunks.append(...), if you can fix that.

Nice catch!

**Comment by TrueMyst** [comment]
LGTM! Let's push it :>

**Comment by TrueMyst** [comment]
Everything looks good so far, but the texts got a bit too much of y-offset. Lemme see if I can fix it.

**Pull request merged**
